title: "Hydra User's Guide"
description: "Comprehensive documentation for the Hydra project."

remote_theme: "just-the-docs/just-the-docs@v0.5.4"

just_the_docs:
  # Enable the theme switcher
  color_scheme_toggle:
    enabled: true
  # Set the default color scheme: light, dark, or auto
  skin:
    color_scheme: auto

# Exclude files from processing
exclude:
  - Gemfile
  - Gemfile.lock
  - node_modules
  - vendor

# Build settings
markdown: kramdown

logo: "/assets/hydra_logo.png"

# In _config.yml
# Color scheme
color_scheme: "dark"

# Custom colors
just_the_docs:
  palette:
    primary:
      hue: "blue"
      saturation: "60%"
      lightness: "50%"
    accent:
      hue: "red"
      saturation: "60%"
      lightness: "50%"