title: "Hydra User's Guide"
description: "Comprehensive documentation for the Hydra project."

remote_theme: "just-the-docs/just-the-docs@v0.5.4"

# Exclude files from processing
exclude:
  - Gemfile
  - Gemfile.lock
  - node_modules
  - vendor

# Build settings
markdown: kramdown

logo: "/assets/hydra_logo.png"

# In _config.yml
# Color scheme
color_scheme: "light"
automatic_dark_mode: false
color_scheme_toggle: true

# Custom colors
just_the_docs:
  palette:
    primary:
      hue: "blue"
      saturation: "60%"
      lightness: "50%"
    accent:
      hue: "215"
      saturation: "65%"
      lightness: "45%"